import Link from 'next/link'
import { siteChrome } from '@/lib/chrome/load'
import { LOGO_PRESET_ART } from '@/lib/chrome/preset-art'
import { logoPreset } from '@/lib/chrome/presets'
import { type BrandChrome, scaledWidth, splitWordmark } from '@/lib/site'

/**
 * The built-in mark. Still hand-drawn, still `currentColor`-free so it follows the accent
 * from Appearance → Theme — and still what renders when the operator has chosen nothing,
 * which is the whole fallback story for docs/15 "Brand and identity".
 */
export function Monogram({ size = 30 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 28 28" aria-hidden="true" className="shrink-0">
      <rect width="28" height="28" rx="7" className="fill-brand" />
      <path
        d="M10 20V8h5a3.8 3.8 0 0 1 0 7.6h-5"
        fill="none"
        className="stroke-brand-ink"
        strokeWidth="2.4"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

/**
 * One of the ten directions from `design/logos/`, chosen in Appearance → Brand.
 *
 * Inlined into the markup rather than fetched as an image: the header is above the fold on
 * every page, so an `<img>` here is a request in the critical path and a chance to shift the
 * layout. The markup comes from `preset-art.ts`, which is generated from files in this
 * repository — never from anything an operator typed — which is what makes inlining it safe.
 */
function PresetMark({ id, size }: { id: string; size: number }) {
  const art = LOGO_PRESET_ART[id as keyof typeof LOGO_PRESET_ART]
  if (!art) return <Monogram size={size} />
  return (
    <span
      aria-hidden="true"
      className="inline-flex shrink-0"
      style={{ width: size, height: size }}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: build-time SVG from design/logos, generated by design/logos/emit-preset-art.mjs, never operator input
      dangerouslySetInnerHTML={{ __html: art.replace('<svg', '<svg width="100%" height="100%"') }}
    />
  )
}

/**
 * The uploaded mark.
 *
 * Both the dark- and light-background logos are in the markup and CSS picks between them
 * (`.brand-logo-*` in globals.css). The theme is decided by a script before first paint, so a
 * server-rendered choice would be wrong half the time and a client-side swap would flash;
 * two `<img>` tags, one of them `display:none`, cost a few hundred bytes and are always
 * right. Explicit width/height come from the confirm step so the header reserves the box.
 */
function LogoImages({ brand, height }: { brand: BrandChrome; height: number }) {
  const dark = brand.logoDark
  const light = brand.logoLight
  // The link already carries an accessible name, so the images are decorative.
  const img = (asset: NonNullable<BrandChrome['logoDark']>, className: string) => (
    <img
      src={asset.url}
      alt=""
      width={scaledWidth(asset, height)}
      height={height}
      className={`${className} shrink-0 object-contain`}
      style={{ height }}
    />
  )
  if (dark && light) {
    return (
      <>
        {img(dark, 'brand-logo-dark block')}
        {img(light, 'brand-logo-light')}
      </>
    )
  }
  const only = dark ?? light
  // One upload has to serve both themes, so it must not carry a swap class.
  return only ? img(only, 'block') : null
}

/**
 * The header/footer wordmark (docs/15): logo only · logo + name · name only.
 *
 * The mark has three sources, in this order: one of the ten built-in logo directions if the
 * operator picked one, then their own upload, then the hand-drawn monogram the site has always
 * shipped. So "logo only" is never nothing, and an operator who has configured nothing sees
 * exactly what they saw before Appearance existed.
 *
 * `brand` is passed down by the header and footer, which already have the resolved chrome;
 * the auth pages render it standalone and let it read the chrome itself.
 */
export async function Wordmark({
  size = 'md',
  brand,
}: {
  size?: 'sm' | 'md'
  brand?: BrandChrome
}) {
  const b = brand ?? (await siteChrome()).brand
  const markSize = size === 'sm' ? 24 : 30
  const showMark = b.wordmark !== 'name'
  const showName = b.wordmark !== 'logo'
  const [lead, rest] = splitWordmark(b.name)
  const preset = logoPreset(b.logoPreset)
  const hasLogo = !!(b.logoDark ?? b.logoLight)
  return (
    <Link
      href="/"
      aria-label={`${b.name} home`}
      className="flex items-center gap-2.5 rounded-md text-fg"
    >
      {showMark ? (
        preset ? (
          <PresetMark id={preset.id} size={markSize} />
        ) : hasLogo ? (
          <LogoImages brand={b} height={markSize} />
        ) : (
          <Monogram size={markSize} />
        )
      ) : null}
      {showName ? (
        <span
          className={`font-display font-extrabold leading-none tracking-[-0.04em] ${
            size === 'sm' ? 'text-[17px]' : 'text-[21px]'
          }`}
        >
          {lead}
          {rest ? <span className="font-normal tracking-[-0.02em]">{rest}</span> : null}
        </span>
      ) : null}
    </Link>
  )
}
