import { sql } from 'drizzle-orm'
import {
  type AnyPgColumn,
  bigint,
  check,
  index,
  integer,
  pgTable,
  primaryKey,
  text,
  uniqueIndex,
} from 'drizzle-orm/pg-core'
import { createdAt, identity, ref, timestamptz, updatedAt } from './_shared.js'
import { series } from './catalog.js'
import { bytea } from './custom-types.js'
import { seriesType } from './enums.js'
import { users } from './identity.js'

/**
 * The series request board (migration 9024). One row per *title* anybody has asked for, and
 * a vote per person beside it — not one row per person who asked, which is what a suggestion
 * inbox degenerates into and which tells the operator nothing about demand.
 *
 * The rules that matter are in the database, not in the route handlers:
 *
 *   * `titleKey` is generated from `title` (lower case, letters and digits only) and unique,
 *     so the same title can only ever have one row however many requests race for it;
 *   * `seriesRequestVotes` is keyed by `(requestId, voterKey)`, so one identity is one vote;
 *   * `voteCount` is a denormalised counter maintained by a statement-level trigger, exactly
 *     like `series.chapterCount` (migration 0002).
 */
export const REQUEST_STATUSES = ['open', 'planned', 'added', 'declined', 'exists'] as const
export type RequestStatus = (typeof REQUEST_STATUSES)[number]

export const seriesRequests = pgTable(
  'series_requests',
  {
    id: identity(),
    title: text('title').notNull(),
    /** Normalised dedupe key, generated by Postgres so it can never drift from `title`. */
    titleKey: text('title_key').generatedAlwaysAs(
      sql`regexp_replace(lower(title), '[^a-z0-9]+', '', 'g')`,
    ),
    altTitles: text('alt_titles').array().notNull().default(sql`'{}'::text[]`),
    /** MangaUpdates / AniList / official page — whatever lets staff identify the title. */
    link: text('link'),
    type: seriesType('type'),
    note: text('note'),
    /** open | planned | added | declined | exists — see `REQUEST_STATUSES`. */
    status: text('status').$type<RequestStatus>().notNull().default('open'),
    /** Public: shown under a declined row so the board answers instead of ignoring. */
    declineReason: text('decline_reason'),
    /** What fulfils it ('added') or what it already was ('exists'); required for both. */
    seriesId: ref('series_id').references(() => series.id, { onDelete: 'set null' }),
    /** Set when staff fold this row into another; merged rows leave the board. */
    mergedIntoId: bigint('merged_into_id', { mode: 'number' }).references(
      (): AnyPgColumn => seriesRequests.id,
      { onDelete: 'set null' },
    ),
    /** The requester when they were signed in — the reason we can tell them the outcome. */
    userId: ref('user_id').references(() => users.id, { onDelete: 'set null' }),
    /** HMAC of whoever filed it; an address never reaches the table. */
    requesterKey: bytea('requester_key'),
    voteCount: integer('vote_count').notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    resolvedAt: timestamptz('resolved_at'),
    resolvedBy: ref('resolved_by').references(() => users.id, { onDelete: 'set null' }),
  },
  (t) => [
    uniqueIndex('series_requests_title_key_uidx').on(t.titleKey),
    index('series_requests_board_idx')
      .on(t.status, t.voteCount.desc(), t.createdAt.desc())
      .where(sql`${t.mergedIntoId} IS NULL`),
    index('series_requests_newest_idx')
      .on(t.createdAt.desc())
      .where(sql`${t.mergedIntoId} IS NULL`),
    index('series_requests_title_trgm_idx').using('gin', t.title.op('gin_trgm_ops')),
    index('series_requests_series_idx').on(t.seriesId).where(sql`${t.seriesId} IS NOT NULL`),
    index('series_requests_user_idx')
      .on(t.userId, t.createdAt.desc())
      .where(sql`${t.userId} IS NOT NULL`),
    index('series_requests_merged_idx')
      .on(t.mergedIntoId)
      .where(sql`${t.mergedIntoId} IS NOT NULL`),
    check('series_requests_title_check', sql`length(btrim(${t.title})) BETWEEN 2 AND 200`),
    check(
      'series_requests_status_check',
      sql`${t.status} IN ('open', 'planned', 'added', 'declined', 'exists')`,
    ),
    check(
      'series_requests_fulfilled_check',
      sql`${t.status} NOT IN ('added', 'exists') OR ${t.seriesId} IS NOT NULL`,
    ),
    check('series_requests_alt_titles_check', sql`cardinality(${t.altTitles}) <= 10`),
  ],
)

/**
 * One vote per *identity* per request — the primary key, not an application check.
 *
 * `voterKey` is `HMAC(secret, 'rq:v1|' || identity)` truncated to 16 bytes: the account id
 * for a signed-in reader, the client address for everyone else. There is deliberately no day
 * bucket in it (unlike `viewEvents.viewerKey`), because a key that rotated daily would hand
 * every anonymous reader a fresh vote every morning.
 *
 * Identity, not person: a reader who votes anonymously and then signs in has two of them and
 * leaves two rows. Migration 9024 has the full argument for why that is left alone — finding
 * the anonymous row means keying on an address, and addresses are shared.
 */
export const seriesRequestVotes = pgTable(
  'series_request_votes',
  {
    requestId: ref('request_id')
      .notNull()
      .references(() => seriesRequests.id, { onDelete: 'cascade' }),
    voterKey: bytea('voter_key').notNull(),
    userId: ref('user_id').references(() => users.id, { onDelete: 'set null' }),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.requestId, t.voterKey] }),
    // One account, one row, whatever `voterKey` says — which matters when the key changes and
    // the account does not: a rotated app secret, or a merge moving rows keyed under an older
    // one. It does *not* fuse an anonymous vote with a later signed-in one; see above.
    uniqueIndex('series_request_votes_user_uidx')
      .on(t.requestId, t.userId)
      .where(sql`${t.userId} IS NOT NULL`),
    index('series_request_votes_voter_idx').on(t.voterKey),
  ],
)
