import { getDb, publishedAppearance } from '@palscans/db'
import { unstable_cache } from 'next/cache'

/**
 * docs/15 step 2: the published token block, inlined in <head> so there is no extra request
 * and no flash of the old theme. Cached and tagged `appearance`; publishing from
 * Appearance → Theme calls `revalidateTag('appearance')`. Empty when the database is
 * unreachable so the shell still renders with the compiled defaults.
 */
export const cachedAppearanceCss = unstable_cache(
  async (): Promise<string> => {
    try {
      const row = await publishedAppearance(await getDb())
      return row?.resolvedCss ?? ''
    } catch {
      return ''
    }
  },
  ['appearance', 'css'],
  { revalidate: 300, tags: ['appearance'] },
)

export async function AppearanceStyle() {
  const css = await cachedAppearanceCss()
  if (!css) return null
  // The block is generated by lib/appearance/resolve.ts from validated hex values — never user markup.
  return (
    // biome-ignore lint/security/noDangerouslySetInnerHtml: token block from the resolver (validated hex/px values), not user markup
    <style id="appearance" dangerouslySetInnerHTML={{ __html: css.replace(/<\/style/gi, '') }} />
  )
}
